### PR TITLE
Experimental WebDriver support

### PR DESCRIPTION
**Pull request by aristotelos**
This pull request is to invite feedback on if we could add WebDriver capabilities to FlaUI. I was driven to this by the fact that Windows WinAppDriver has many shortcomings and basic issues, and my team would rather use TypeScript than C# for test automation.

Feedback is invited on:

1.  Is this OK to be added to FlaUI? For me and probably others too, this would be the sole reason of using FlaUI.
2. Do you see any blockers that will arise to provide WebDriver2 support via FlaUI?
3. I think it would be easiest to test this by using the Selenium C# client and use a real application like Calculator. I would like to add those tests and then I think the quality provided should be sufficient for an experimental WebDriver implementation.

### CODE REVIEW

**Comment by Roemer** [comment]
Really cool! In general, I am all in for it. I will have a deeper look at the code within the next days.

**Comment by aristotelos** [comment]
I've added some tests using the Selenium C# client and the test WPF application. The tests certainly do not cover all functionality yet, and there are some limitations to the current implementation such as that it does not support all key down input characters, so anyone is welcome to contribute further to them.

**Comment by aristotelos** [comment]
@Roemer I don't know why the build is failing, could you have a look?

**Comment by aristotelos** [comment]
@Roemer Let me know if you need any other information for the review.

**Comment by aristotelos** [comment]
@Roemer Happy new year and best wishes for 2024! Do you have any initial feedback for this merge request?

**Comment by Roemer** [comment]
> @aristotelos, are you open to trying to ship this independently from FlaUI? It could help speed up dev and release cycles.

Good point, I am still looking at the code but having it in an own project (in the FlaUI group), we would have much flexibler possibilities to publish the library independent from the FlaUI version. I could even easier add maintainers there to allow publishing.

**Comment by aristotelos** [comment]
> > @aristotelos, are you open to trying to ship this independently from FlaUI? It could help speed up dev and release cycles.
> 
> Good point, I am still looking at the code but having it in an own project (in the FlaUI group), we would have much flexibler possibilities to publish the library independent from the FlaUI version. I could even easier add maintainers there to allow publishing.

Sounds good to me.

**Comment by Roemer** [comment]
I created https://github.com/FlaUI/FlaUI.WebDriver and added @aristotelos with write permissions. Could you move the corresponding code there (just leave the other changes here so I can merge them)? If that is done, I will set up the automatic publish pipeline.

**Comment by aristotelos** [comment]
@Roemer I've pushed the code to https://github.com/FlaUI/FlaUI.WebDriver. I'll close this PR now; it contained one small modification to the UIA3 code but I decided to revert that.

**Pull request closed without merging**
